source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

inhibit_all_warnings!

post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end

target 'SSImageBrowser_Example', :exclusive => true do
  pod "SSImageBrowser", :path => "../"
end

#target 'SSImageBrowser_Tests', :exclusive => true do
#  pod "SSImageBrowser", :path => "../"
#
#  pod 'Quick', '~> 0.6.0'
#  pod 'Nimble', '~> 2.0.0-rc.3'
#  pod 'FBSnapshotTestCase'
#  pod 'Nimble-Snapshots', '~> 1.0.0'
#end
