source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
target 'SSImageBrowser_Example', :exclusive => true do
  pod "SSImageBrowser", :path => "../"
end

target 'SSImageBrowser_Tests', :exclusive => true do
  pod "SSImageBrowser", :path => "../"

  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '~> 2.0.0-rc.3'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots', '~> 1.0.0'
end
